<?php
namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\API\BaseController as BaseController;

class CommonController extends BaseController
{
    /**
     * Get random number.  (created date: 13-02-2020, created by: Tridhya Tech)
     * @param  Request  $request
     * @return [json] random number as array
     * @return [int] status_code
     * @return [bool] success
     * @return [string] message
    */
    public function getGuestRandomNumber(Request $request) {

        $autogeneratednumber = 'guest_'.$this->randomNumber();
        $records = [
            "guestNumber" => $autogeneratednumber
        ];
    
        $status_code = config('response_status_code.random_number_fetched_success');
        return $this->sendResponse(true, $status_code, trans('message.random_number_fetched_success'), $records);
    }

    /**
     * Generate random number 
     *
     * @return [string] numberword
     */
    public function randomNumber() {
        $digit = '1234567890';
        $number = array(); //remember to declare $number as an array
        $digitLength = strlen($digit) - 1; //put the length -1 in cache
        for ($i = 0; $i < 6; $i++) {
            $n = rand(0, $digitLength);
            $number[] = $digit[$n];
        }
        return implode($number); //turn the array into a string
    }

}
